Opal.modules["yaml"] = function(Opal) {/* Generated by Opal 1.8.1 */
  var self = Opal.top, nil = Opal.nil;

  Opal.add_stubs('warn');
  return self.$warn("REMOVED: use `require 'nodejs/yaml'` instead")
};
