/* Generated by Opal 1.2.0 */
Opal.modules["dir"] = function(Opal) {
  var self = Opal.top, $nesting = [], nil = Opal.nil, $$$ = Opal.$$$, $$ = Opal.$$;

  Opal.add_stubs(['$warn']);
  return self.$warn("Dir is already part of corelib now, you don't need to require it anymore.")
};
