/* Generated by Opal 1.2.0 */
Opal.modules["math"] = function(Opal) {
  var self = Opal.top, $nesting = [], nil = Opal.nil, $$$ = Opal.$$$, $$ = Opal.$$;

  Opal.add_stubs(['$warn']);
  return self.$warn("DEPRECATION: math is now part of the core library, requiring it is deprecated")
};
