Opal.modules["cgi"] = function(Opal) {/* Generated by Opal 1.8.0.alpha1 */
  var $klass = Opal.klass, $module = Opal.module, $def = Opal.def, $nesting = [], nil = Opal.nil;

  Opal.add_stubs('include,extend');
  return (function($base, $super, $parent_nesting) {
    var self = $klass($base, $super, 'CGI');

    var $nesting = [self].concat($parent_nesting), $$ = Opal.$r($nesting);

    
    (function($base) {
      var self = $module($base, 'Util');

      
      
      
      $def(self, '$escapeURIComponent', function $$escapeURIComponent(c) {
        
        return encodeURI(c);
      });
      return $def(self, '$unescapeURIComponent', function $$unescapeURIComponent(c) {
        
        return decodeURI(c);
      });
    })($nesting[0]);
    self.$include($$('Util'));
    return self.$extend($$('Util'));
  })($nesting[0], null, $nesting)
};
