Opal.queue(function(Opal) {/* Generated by Opal 1.7.0 */
  var $module = Opal.module, $const_set = Opal.const_set, $hash2 = Opal.hash2, $nesting = [], nil = Opal.nil;

  Opal.add_stubs('split,[]');
  
  (function($base, $parent_nesting) {
    var self = $module($base, 'RbConfig');

    var $nesting = [self].concat($parent_nesting), $$ = Opal.$r($nesting), versions = nil;

    
    versions = $$('RUBY_VERSION').$split(".");
    return $const_set($nesting[0], 'CONFIG', $hash2(["ruby_version", "MAJOR", "MINOR", "TEENY", "RUBY", "RUBY_INSTALL_NAME", "ruby_install_name", "RUBY_SO_NAME", "target_os", "host_os", "PATH_SEPARATOR", "EXEEXT", "bindir"], {"ruby_version": $$('RUBY_VERSION'), "MAJOR": versions['$[]'](0), "MINOR": versions['$[]'](1), "TEENY": versions['$[]'](2), "RUBY": $$('RUBY_ENGINE'), "RUBY_INSTALL_NAME": $$('RUBY_ENGINE'), "ruby_install_name": $$('RUBY_ENGINE'), "RUBY_SO_NAME": $$('RUBY_ENGINE'), "target_os": "ECMA-262", "host_os": "ECMA-262", "PATH_SEPARATOR": ":", "EXEEXT": "", "bindir": ""}));
  })($nesting[0], $nesting);
  return $const_set($nesting[0], 'RUBY_EXE', "bundle exec exe/opal");
});
