Opal.modules["yaml"] = function(Opal) {/* Generated by Opal 1.3.2 */
  var self = Opal.top, $nesting = [], nil = Opal.nil, $$$ = Opal.$$$, $$ = Opal.$$;

  Opal.add_stubs(['$warn']);
  return self.$warn("REMOVED: use `require 'nodejs/yaml'` instead")
};
