Opal.modules["dir"] = function(Opal) {/* Generated by Opal 1.5.1 */
  var self = Opal.top, nil = Opal.nil;

  Opal.add_stubs('warn');
  return self.$warn("Dir is already part of corelib now, you don't need to require it anymore.")
};
