Opal.modules["encoding"] = function(Opal) {/* Generated by Opal 1.5.1 */
  var self = Opal.top, nil = Opal.nil;

  Opal.add_stubs('warn');
  return self.$warn("DEPRECATION: encoding is now part of the core library, requiring it is deprecated")
};
